theme:
  name: material
  favicon: 'images/profile.jpeg'
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.tabs.sticky
    - navigation.path
    - toc.integrate
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
nav:
  - Home: index.md
  - 框架:
    - Kubernetes:
      - k8s.md
    - Spring: 
      - spring_javaguide.md
      - spring&springboot_annotation_javaguide.md
      - 2023-05-07-spring.md
      - 2023-05-01-spring.md
    - MySQL:
      - mysql_xiaolin.md

  - 语言:
    - Go:
      - go.md
    - Java: 
      - java_multithread_javaguide.md
      - java_jvm_javaguide.md
      - java_javaguide.md
      - java_multithreading_lianglianglee.md
      
  - 算法: 
    - 代码随想录:
      - 代码随想录-Day37.md
      - 代码随想录-Day36.md
      - 代码随想录-Day35.md
      - 代码随想录-Day34.md
      - 代码随想录-Day33.md
      - 代码随想录-Day32.md
      - 代码随想录-Day31.md
      - 代码随想录-Day30.md
      - 代码随想录-Day29.md
      - 代码随想录-Day28.md
      - 代码随想录-Day27.md
      - 代码随想录-Day26.md
      - 代码随想录-Day25.md
      - 代码随想录-Day24.md
      - 代码随想录-Day23.md
      - 代码随想录-Day22.md
      - 代码随想录-Day21.md
      - 代码随想录-Day20.md
      - 代码随想录-Day19.md
      - 代码随想录-Day18.md
      - 代码随想录-Day17.md
      - 2023-05-16-代码随想录-Day16.md
      - 2023-05-15-代码随想录-Day15.md
      - 2023-05-14-代码随想录-Day14.md

    - 英雄算法联盟:
      - 2023-04-30-英雄算法联盟-Day30.md
      - 2023-04-29-英雄算法联盟-Day29.md

    - 训练营:
      - 训练营-Day3.md
      - 训练营-Day2.md
      - 2023-05-15-训练营-Day1.md
  - Online Courses/Readings:
    - Psychology:
      - Introduction to Psychology (Yale):
        - psychology_history_of_psychology.md
        - psychology_research_design.md
        - psychology_the_brain.md

site_name: Yiping's Notes
repo_url: https://github.com/Yiping-Z/notes
site_url: https://yiping-z.github.io/notes/
copyright: Copyright @ Yiping-Z
remote_branch: gh-pages
use_directory_urls: false
extra:
  social:
    - icon: octicons/mark-github-16
      link: https://github.com/Yiping-Z
